name: Reusable
on:
   workflow_call:
    inputs:
      marka:
        description: 'marka'
        required: true
        type: string
env:
  marka: ${{inputs.marka}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}
jobs:
  imageopt:
    if: success() || failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          # ref: master
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
         cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS...
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: 'npm install'
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
      - name: fetchRemoteImages
        run: node utils/fetchRemoteImagesInParallel.js
      - name: Commit report
        run: |
          git config --global user.name 'Serdar Ashirov'
          git config --global user.email 'webapis@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git pull origin main
          git add .
          git commit -m "Automated report."
          git push
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}